learning_templates/BasicApp/urls.py
from django.conf.urls import url
from django.urls import path
from BasicApp import views

app_name = "BasicApp"

urlpatterns = [
    # url(r"^relative/$", views.relative, name="relative"),
    # url(r"^other/$", views.other, name="other"),

    
    # path("relative/", views.relative, name="relative"),
    # path("other/", views.other, name="other"),
    path("register/", views.register, name="register"),
    path("user_login/", views.user_login, name="user_login"),
    
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

from BasicApp import views

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    # url(r'^$', views.index, name="index"),
    # url(r'^BasicApp/', include("BasicApp.urls"))

    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('BasicApp/', include("BasicApp.urls")),
    path('logout/', views.user_logout, name="logout"),
    path("special/", views.special, name="special"),
]

learning_templates/BasicApp/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional fields
    portfolio_site = models.URLField(blank=True) 
    
    profile_pic = models.ImageField(upload_to="profile_pics", blank=True)

    def __str__(self):
        return self.user.username

learning_templates/BasicApp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learning_templates/BasicApp/views.py
from django.shortcuts import render
from BasicApp.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def index(request):
    # context_dict = {"text": "Hello Hamad", "number": "1000"}
    return render(request, "BasicApp/index.html")


@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")


@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if "profile_pic" in request.FILES:
                profile.profile_pic = request.FILES["profile_pic"]

            profile.save()
            registered = True
        else:
            print(user_form.errors)
            print(profile_form.errors)
    else:

        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    context_dic = {
        "user_form": user_form,
        "profile_form": profile_form,
        "registered": registered
    }

    return render(request, "BasicApp/registration.html", context=context_dic)


def user_login(request):

    if request.method == "POST":

        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse("index"))
            else:
                return HttpResponse("Account is not active")
        else:
            print("unsuccesfull login")
            return HttpResponse("invalid login")
    else:
        return render(request, 'BasicApp/login.html')

learning_templates/templates/BasicApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title></title>
</head>
<body>
    
      <nav class="navbar navbar-expand-lg navbar-light bg-light">

        <div class="container">
          
          <a class="navbar-brand" href="">Django</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
              </li>

              <li class="nav-item">
                  <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'BasicApp:register' %}">Register</a>
              </li>

              {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                  </li>
              {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'BasicApp:user_login' %}">LogIn</a>
                  </li> 
              {% endif %}   
            </ul>

            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>

          </div>

        </div>

      </nav>
  
    <div class="container">
        {% block body_block %} 
        <!-- Anything out side oh here will be inherited -->
        {% endblock %}
    </div>
</body>
</html>

learning_templates/templates/BasicApp/index.html
<!DOCTYPE html>
{% extends "BasicApp/base.html" %}
    {% block body_block %}
      <div class="jumbotron">
          <h1>Home Page</h1>
      </div>
    {% endblock %}

learning_templates/templates/BasicApp/login.html
<!DOCTYPE html>
{% extends "BasicApp/base.html" %}
    {% block body_block %}
        <div class="jumbotron">
            <h1>Please Login</h1>
            <br>
            <form action="{% url 'BasicApp:user_login' %}" method="POST">
                
                {% csrf_token %}
                
                <label for="username">Username: </label>
                <input type="text" name="username" placeholder="Enter Username">
                <br>

                <label for="password">Password: </label>
                <input type="password" name="password">
                <br>

                <input type="submit" class="btn btn-primary" value="Login">

            </form>
        </div>
    {% endblock %}

learning_templates/templates/BasicApp/other.html
<!DOCTYPE html>
{% extends "BasicApp/base.html" %}
    {% block body_block %}
        <h1>Other Page</h1>
    {% endblock %}

learning_templates/templates/BasicApp/registration.html
<!DOCTYPE html>
{% extends "BasicApp/base.html" %}
    {% block body_block %}
      <div class="jumbotron">
            {% if registered %}
                <h1>Thanks for Registration</h1>
            {% else %}
                <h1>Register Here Please</h1>
                <h3>Fill out the Form:</h3>
            
                <form enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    {{ user_form.as_p }}
                    {{ profile_form.as_p }}
                    <input type="submit" class="btn btn-primary" value="Register">
                </form>
            {% endif %}
      </div>
    {% endblock %}

learning_templates/templates/BasicApp/rel_temps.html
<!DOCTYPE html>
{% extends "BasicApp/base.html" %}
    {% block body_block %}
        <h1>Rel URL Temps Page</h1>
        <a href="{% url 'BasicApp:other' %}">Other Page</a>
        <br>
        <a href="{% url 'admin:index' %}">Admin</a>
        <br>
        <a href="{% url 'index' %}">Index</a>
    {% endblock %}